name: FreedomOpMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.0
description: Plugin for the FreedomOP server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, DisguiseCraft, BarAPI, CoreProtect]
authors: [Madgeek1450, DarthSalamon, Camzie99, RobinGall2910, PieGuy7896]

# plugin.yml is no longer used to define commands.
